name: testdb
services:
  postgres:
    container_name: postgres_container
    image: postgres:16
    environment:
      POSTGRES_DB: "testdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres_network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:8.11.0
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres_network

volumes:
  postgresql:
  pgadmin-data:

networks:
  postgres_network:
    driver: bridge